version: "3.8"

services:
  server:
    # image: nginx:stable-alpine
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      # - ./logs/:/var/log
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      args:
        user: andere
        uid: 1000
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/wwww/html:delegated #delegated - optimizes writes to reduce frequency
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env/mysql.env
  composer: #utility container
    build:
      context: ./dockerfiles
      args:
        user: andere
        uid: 1000
        gid: 1000
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      args:
        user: andere
        uid: 1000
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
