apiVersion: v1
kind: Service
metadata:
  name: eks-auth-api-service
spec:
  selector:
    app: eks-auth-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-auth-api
  template:
    metadata:
      labels:
        app: eks-auth-api
    spec:
      containers:
        - name: auth-api
          image: briancollins081/eks-auth-api:latest
          env:
            - name: TOKEN_KEY
              value: 'shouldbeverysecure'
