apiVersion: v1
kind: Service
metadata:
  name: eks-tasks-api-service
spec:
  selector:
    app: eks-tasks-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-tasks-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-tasks-api
  template:
    metadata:
      labels:
        app: eks-tasks-api
    spec:
      containers:
        - name: tasks-api
          image: briancollins081/eks-tasks-api:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://awsRootAdmin:Y7CKDuOm1nmQxMlM@awscluster.1lc4s.mongodb.net/aws-eks?retryWrites=true&w=majority"
            - name: AUTH_API_ADDRESS
              value: "eks-auth-api-service.default:3000"
