kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persistent-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-2a8ffd52
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: eks-users-api-service
spec:
  selector:
    app: eks-users-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-users-api
  template:
    metadata:
      labels:
        app: eks-users-api
    spec:
      containers:
        - name: users-api
          image: briancollins081/eks-users-api:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://awsRootAdmin:Y7CKDuOm1nmQxMlM@awscluster.1lc4s.mongodb.net/aws-eks?retryWrites=true&w=majority"
            - name: AUTH_API_ADDRESS
              value: "eks-auth-api-service.default:3000"
          volumeMounts:
            - name: efs-volume
              mountPath: /app/users
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-persistent-volume-claim
