version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    ports:
      - "8080:8080"
    environment:
      AUTH_HOST: auth
      AUTH_SERVICE_SERVICE_HOST: auth #if using docker generated env vars inside app
  tasks:
    build: ./tasks-api
    ports:
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
