apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimg-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: authapi
          image: briancollins081/multimg-auth-api:latest
