apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimg-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-react
          image: briancollins081/multimg-frontend:latest
