apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
  labels:
    group: samples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      func: nodejs-app
    # matchExpressions:
    #   - { key: app, operator: In, values: [second-app, first-app] }
  template:
    metadata:
      labels:
        app: second-app
        func: nodejs-app
    spec:
      containers:
        - name: second-nodejs-container
          image: briancollins081/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
