apiVersion: v1
kind: Service
metadata:
  name: app-2-service
  labels:
    group: samples
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 81
      targetPort: 8080
    # - protocol: "TCP"
    #   port: 82
    #   targetPort: 8080
  type: LoadBalancer
