apiVersion: v1
kind: Service
metadata:
  name: app-2-service
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 81
      targetPort: 8080
    # - protocol: "TCP"
    #   port: 82
    #   targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      func: nodejs-app
  template:
    metadata:
      labels:
        app: second-app
        func: nodejs-app
    spec:
      containers:
        - name: second-nodejs-container
          image: briancollins081/kub-first-app:2
