apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-demo
  template:
    metadata:
      labels:
        app: data-demo
    spec:
      containers:
        - name: story
          image: briancollins081/story-app-volumes-demo:2
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir volume type
          # emptyDir: {}
          # hostPath volume type
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # persistent volume type of hostPath
          persistentVolumeClaim:
            claimName: hostpath-pvc
